### ISSUE TITLE
Status of repo?

### ISSUE THREAD

**Issue by orenf** [adamfortuna/avalara#11]
Hi Adam,

We've been using your gem for some time. Recently,  I've made a number of minor updates to the gem in order to make it work with Ruby 2.2.1. Not sure what the status is and if you are interested in receiving our pull request for the changes we made. 

Thanks.

**Comment by adamfortuna** [comment]
Ohh, thanks -- i'd be up for it. I would say i'm a pretty bad maintainer of this one, as i haven't been using it professionally and don't currently have it running locally. I'd be up for either merging these in, or if you'd be up for it -- adding additional collaborators after accepting a pull request.

What kind of version bump would you expect your changes to introduce? A major, minor or patch level?

**Comment by orenf** [comment]
Hi Adam,

Thanks for getting back to me so quickly.  It would be a minor version patch. I didn't add any new features, just made the existing features work. Here, take a look, let me know what you think?  You'll notice that I removed support for some of the older ruby versions.

https://github.com/chloeandisabel/avalara

**Comment by adamfortuna** [comment]
Ah nice, do you think you could do a pull request from your repo back to this one (master) ? That'll make it super easy to see what's changed.

**Comment by orenf** [comment]
Great. You should have the pull request now. Take a look, you'll have some
questions I'm sure. Fire away.
Also, I'd be happy to be a contributor.

Oren

**Comment by adamfortuna** [comment]
I merged in @orenf changes, including Ruby 2x support, hashie and httparty updates and a few more!
