### ISSUE TITLE
Allow specifying a request timeout

### ISSUE THREAD

**Issue by Tonkpils** [adamfortuna/avalara#16]
We should be able to set a request timeout for the Avalara API. Currently, I see no way of specifying it. This could be at a global configuration level or on a per request basis. 

What are your thoughts for this?

**Comment by adamfortuna** [comment]
Sounds like a good idea!

I'm not actively working on this gem at the moment, but I'd be open to adding this via pull requests with tests if you'd like to try making one.

**Comment by Tonkpils** [comment]
Sure, I'll gladly make a PR.
