### ISSUE TITLE
Add Address Validation

### ISSUE THREAD

**Issue by MMartyn** [adamfortuna/avalara#2]
I'd like to add in address validation. Looking at the address that the validation call takes and the address that the tax call takes I think it would be best to create a base_address that can be used for the validation call and extended for the tax call.

**Comment by Tonkpils** [comment]
@MMartyn is this still a valid Issue? I've implemented the address validation API Avalara provides   and using it in production for a few of months now. Unless there's anything else you'd like to see I'm closing this issue. Feel free to re-open and comment!
