### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by Showtimes** [adamfortuna/avalara#21]
Build seems to be failing. I'll be a new customer soon and was wondering if this has been tested on rails 5.

**Comment by adamfortuna** [comment]
Should work with Rails 5, but haven't tested things. We don't have a dependency on any version of rails.

The build is failing as you said though. :/ The current pushed gem was for a working build, but master is currently not in a happy state (something I need to cleanup).

**Comment by adamfortuna** [comment]
I'm _assuming_ things will work on rails 5 -- but if someone runs into an issue with it, feel free to open an issue for it!
