### ISSUE TITLE
Hashie uninitialized constant

### ISSUE THREAD

**Issue by thewalkingtoast** [adamfortuna/avalara#23]
A recent install of the avalara gem installs hashie 3.5.5 which, when running `Avalara::Request::Invoice.new`, produces:

```ruby
uninitialized constant Hashie::Extensions::Coercion::RubyVersion
```

Locking hashie to 3.4.6 does not produce the issue.

OS: macOS 10.12.3
Ruby: 2.3.3

**Comment by Tonkpils** [comment]
Great catch, it seems to have been an issue before to have hashie unlocked like this. Would you mind making a PR for this? Otherwise, I can probably get to it soon

**Comment by thewalkingtoast** [comment]
@Tonkpils Opened ^ Thanks!
