### ISSUE TITLE
Pull request (simple refactor) after tests

### ISSUE THREAD

**Issue by nearapogee** [adamfortuna/avalara#5]
Hi. Thanks for the great library. It has been working great.

However, a simple refactoring of moving all the Avalara class methods into a module, would make everything much more flexible. This was induced by a project requirement.

You can see my diff here:
https://github.com/nearapogee/avalara/commit/86bc53ad283ad7f2e1196452d0dfd02aea7e8e1e

I would like to make a pull request, but VCR is giving me grief. I only get an error message:

```shell
 Real HTTP connections are disabled. Unregistered request: POST https://xxx:xxx@rest.avalara.net/1.0/tax/get
```

(redaction mine)

And an advertisement, with a broken link:

```shell
You can use VCR to automatically record this request and replay it later.  For more details, visit the VCR documentation at: http://relishapp.com/myronmarston/vr/v/1-11-3
```

I have used VCR a couple times in the past, but I generally don't use it or RSpec. Could you shed some wisdom on this for me so I can confirm the specs are good?

**Comment by adamfortuna** [comment]
Going to close this one out as inactive! Feel free to open it up again, or start a PR.
